apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zcu43ineu-go
  janus-idp.io/tekton: zcu43ineu-go
  backstage.io/kubernetes-id: zcu43ineu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zcu43ineu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
