apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zcu43ineu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zcu43ineu-go 
  name: zcu43ineu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zcu43ineu-go 
