apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zcu43ineu-go-gitops
  description: This is GitOps manifest for zcu43ineu-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=zcu43ineu-go
    backstage.io/kubernetes-id: zcu43ineu-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: zcu43ineu-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zcu43ineu-go
